package com.ospavliuk.myvaadintest;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MyUIDesigner extends VerticalLayout {
    protected Label label;
    protected HorizontalLayout horizontalLayout;
    protected TextArea textArea;
    protected Button _1;
    protected Button _2;
    protected Button _3;
    protected Button _4;
    protected Button _5;
    protected Button _6;
    protected Button _7;
    protected Button _8;
    protected Button _9;
    protected Button back;
    protected Button _0;
    protected Button enter;
    protected Button startButton;

    public MyUIDesigner() {
        Design.read(this);
    }
}
