package com.ospavliuk.myvaadintest;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextField;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.FormLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MyUIDesigner extends VerticalLayout {
    protected Label label;
    protected HorizontalLayout horizontalLayout;
    protected HorizontalLayout gameProgres;
    protected TextArea userArea;
    protected TextArea robotArea;
    protected VerticalLayout controlPanel;
    protected HorizontalLayout inputLayout;
    protected TextField numberField;
    protected TextField scoreField;
    protected GridLayout keyboardLayout;
    protected Button _1;
    protected Button _2;
    protected Button _3;
    protected Button _4;
    protected Button _5;
    protected Button _6;
    protected Button _7;
    protected Button _8;
    protected Button _9;
    protected Button back;
    protected Button _0;
    protected Button enter;
    protected Button startButton;
    protected FormLayout settingsLayout;
    protected ComboBox<String> gameCombo;
    protected ComboBox<String> numberCombo;
    protected TextField overallScore;
    protected TextArea infoArea;

    public MyUIDesigner() {
        Design.read(this);
    }
}
